ccflags-y := -O3 -mcpu=cortex-a15 -mtune=cortex-a15 -marm -mfpu=neon-vfpv4 -mvectorize-with-neon-double -munaligned-access -ffast-math -floop-block -floop-interchange -floop-nest-optimize -floop-parallelize-all -floop-strip-mine
obj-y += msm_ion.o ion_cp_common.o
